### ISSUE TITLE
[QUESTION]: is it possible to update a nextcloud installation to the newest version?

### ISSUE THREAD

**Issue by klemens-u** [aalaesar/install_nextcloud#100]
Can this role do it?
If so, how exactly?

If not, any hints or experience on how to automate it?

Thanks!

**Comment by aalaesar** [comment]
Hello,
Sorry to answer so late.
Actually no. Upgrade

**Comment by aalaesar** [comment]
Hello @Klemens-u,
Sorry for this late answer (covid,  etc)

Actually no. The role only do first install and it's a shame. Another role has been made for the upgrade process, some years ago but I suppose it is now obsolete. 
Nexcloud update is a relative "simple" process:
0. Optionally Upgrade PHP
1. Set oc on maintenance mode
2. Backup de database
3. Download the desired release and verify the download unzip/tar
4. Move the old version somewhere else
5. Move the new version in place of the old
6. Run the upgrade command, Optionally all occ maintenance command to update database indexes etc
7. Disable maintenance mode
8. Upgrades / reinstall all the previous applications.
Verify everything is ok
Clean-up, or not

To be trusted, the role also need to rollback at any failure in order to not leave the application in a unavailable state
- Restore old files
- Restore the database
- restore PHP version

 that's where come the complexity.

Given the complexity and the number of case I think  a role is not enough to do all this.
I'm looking into upgrading the role into a collection to use simpler role to manage multiple use case, upgrade included

Something is the mind of kubespray.

**Comment by staticdev** [comment]
I think this is answered.
