### ISSUE TITLE
Allow usage on port 80 behind proxy

### ISSUE THREAD

**Issue by noplanman** [aalaesar/install_nextcloud#16]
I use this role to set up Nextcloud on a server that sits behind a Nginx reverse proxy.

The proxy manages all TLS certificate stuff and basically just needs to connect to a simple port 80 webserver that is hosting the Nextcloud instance.

Would be nice to have an option to allow this setup, instead of forcing TLS.

I'm happy to PR this if you like, as I use this in my setup anyway 👍

**Comment by aalaesar** [comment]
Hi @noplanman,
The role is indeed quite rigid on TLS/HTTP configuration as it was initially intended for single server installation close to nextcloud recommandations. The http patterns have only slightly changed since the initial commit.
I initially intended to work around this limitation with issue #5 , but I have'nt yet found a good way to do it.
you're welcome to PR anyway :-)
Regards.

**Comment by noplanman** [comment]
Ok, I'll clean up my local version and make a PR.

It will go hand in hand with the new `nextcloud_install_tls` option too.
